### ISSUE TITLE
Consider sending the response earlier in the `handler`-method

### ISSUE THREAD

**Issue by FalkWasTaken** [DD2480-Group31/Continuous-Integration#40]
I see that we quite often get timeouts on the webhook request. This is probably due to the fact that we don't send the response until after we've run all tests. It might be more correct to respond first, saying that we've received the request and are processing it.

**Comment by sebveij** [comment]
I agree, we can move it.

**Comment by FalkWasTaken** [comment]
I found a useful guide [here](https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#favor-asynchronous-work-over-synchronous)
