### ISSUE TITLE
Don't process the request if `after`-parameter is zero

### ISSUE THREAD

**Issue by FalkWasTaken** [DD2480-Group31/Continuous-Integration#42]
I don't think we should process requests when the `after`-parameter is zero. I think those commits refer to the merges and should probably not be tested/built.

**Comment by FalkWasTaken** [comment]
I'm not really sure though

**Comment by sebveij** [comment]
Yes. We could probably also add more checks, e.g. that the variables we read from the JSON are not corrupted etc.
